version: "3.9"

services:
  web:
    build:
      context: .
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"  # Only expose port 7999
    volumes:
      - django_data:/app/data
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - shared_network

volumes:
  django_data:

networks:
  shared_network:
    external: true

